name: update content submodule
on:
  repository_dispatch:
    types: [obsidian-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.OBSIDIAN_QUARTZ_TOKEN }}

      - name: update submodule
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git submodule update --remote --merge content

          if git diff --staged --quiet; then
            echo "No updates available"
          else
            git commit -m "🔄 Update obsidian content submodule"
            git push
          fi
